# Schema for the configuration files of the Related Article module.

related_articles.settings:
  type: config_object
  label: 'Related Article settings'
  mapping:
    total_articles:
      type: integer
      label: 'Total number of articles in a block'